### ISSUE TITLE
Use macvendors.com API for lookup

### ISSUE THREAD

**Issue by radriaanse** [radriaanse/checkmac#1]
We should use the API from macvendors.com to perform the lookup.
Theire API is free, but limited to 10K requests per day.

https://macvendors.com/api

**Comment by va6996** [comment]
There is no code available. Does it need to be created or something?

**Comment by radriaanse** [comment]
@va6996 Yea, kinda forgot about this project ;p
I've just committed some stuff, if you want you can fix my "pro" go skills :)

**Comment by va6996** [comment]
lol. I dont know go.
